### ISSUE TITLE
Increase timeout

### ISSUE THREAD

**Issue by paulojmdias** [laixintao/prometheus-http-sd#52]
Hi 👋 

```
  File "/opt/homebrew/lib/python3.11/site-packages/prometheus_http_sd/decorator.py", line 232, in wrapper
    raise TimeoutException("target function timeout!")
prometheus_http_sd.decorator.TimeoutException: target function timeout!
```

We have a function that is entering timeout, Do we have any way to increase the timeout value?

I have tried like the example below but without success

```py
def generate_targets(**extra_parameters):
    decorator.TimeoutDecorator(timeout=300)
    x = main()
    print(x)
    return x
```

**Comment by laixintao** [comment]
Hi @paulojmdias thanks for the issue

I think currently `60s` was hard coded in the decorator config here: https://github.com/laixintao/prometheus-http-sd/blob/223f70c60fb66192c57e60750a5b7ca45ac4f1fb/prometheus_http_sd/sd.py#L150

Let us see if we can make it configurable.

But be careful, the vmagent or prometheus usually set a 60s by default, which means that even your script can run more than 60 seconds, the client side will abort the request on 60seconds.

**Comment by laixintao** [comment]
new version released: https://github.com/laixintao/prometheus-http-sd/tree/v1.3.3
